name: Generate GitHub metrics

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/metrics.yml

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: riddhixraina
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          plugin_languages: "no"
          filename: github-metrics.svg
          config_timezone: America/New_York
          committer_branch: main
          committer_message: "chore: update github metrics"
